package v8dist

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// LinkFileName is the name of the generated per-target cgo file. The zz_ prefix
// keeps it last alphabetically; it is gitignored (see .gitignore).
func LinkFileName(goos, goarch string) string {
	return fmt.Sprintf("zz_generated_v8link_%s_%s.go", goos, goarch)
}

// ldflags returns the linker flags for a target given the resolved -L value.
func ldflags(goos, libPath string) string {
	switch goos {
	case "darwin":
		// ld64 rescans archives, so no --start-group is needed.
		return fmt.Sprintf("-L%s -lv8go_glue -lv8_monolith -lv8_libcxx "+
			"-framework CoreFoundation -lpthread", libPath)
	default: // linux and other ELF platforms
		// Wrap the archives in a group so ld resolves the cross-references
		// between the glue, the monolith, and Chromium's libc++/libc++abi.
		return fmt.Sprintf("-L%s -Wl,--start-group -lv8go_glue -lv8_monolith -lv8_libcxx "+
			"-Wl,--end-group -lm -ldl -lrt -latomic -lpthread", libPath)
	}
}

// writeLinkFile writes the per-target cgo link file into opts.LinkOut and
// returns its path. The -L path is ${SRCDIR}-relative when possible (portable),
// falling back to an absolute path otherwise.
func writeLinkFile(opts *Options, libDir string) (string, error) {
	linkOut, err := filepath.Abs(opts.LinkOut)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(linkOut, 0o755); err != nil {
		return "", err
	}

	pkg := opts.LinkPkg
	if pkg == "" {
		pkg = detectPackageName(linkOut)
	}

	libAbs, err := filepath.Abs(libDir)
	if err != nil {
		return "", err
	}
	libPath := libAbs
	if rel, err := filepath.Rel(linkOut, libAbs); err == nil {
		libPath = "${SRCDIR}/" + filepath.ToSlash(rel)
	}

	content := renderLinkFile(pkg, opts.GOOS, opts.GOARCH, ldflags(opts.GOOS, libPath))
	path := filepath.Join(linkOut, LinkFileName(opts.GOOS, opts.GOARCH))
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func renderLinkFile(pkg, goos, goarch, flags string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "//go:build %s && %s\n\n", goos, goarch)
	b.WriteString("// Code generated by v8setup (go generate); DO NOT EDIT.\n")
	b.WriteString("// It links the prebuilt V8 libraries fetched into .v8/ and is gitignored.\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintf(&b, "// #cgo LDFLAGS: %s\n", flags)
	b.WriteString("import \"C\"\n")
	return b.String()
}

// detectPackageName reads the package clause from an existing .go file in dir,
// falling back to a sanitized directory base name.
func detectPackageName(dir string) string {
	entries, err := os.ReadDir(dir)
	if err == nil {
		for _, e := range entries {
			name := e.Name()
			if e.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
				continue
			}
			if strings.HasPrefix(name, "zz_generated_v8link_") {
				continue
			}
			if pkg := packageClause(filepath.Join(dir, name)); pkg != "" {
				return pkg
			}
		}
	}
	return sanitizeIdent(filepath.Base(dir))
}

func packageClause(path string) string {
	f, err := os.Open(path)
	if err != nil {
		return ""
	}
	defer f.Close()
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if strings.HasPrefix(line, "package ") {
			fields := strings.Fields(line)
			if len(fields) >= 2 {
				return fields[1]
			}
		}
	}
	return ""
}

func sanitizeIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_':
			b.WriteRune(r)
		case r >= '0' && r <= '9' && i > 0:
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	out := b.String()
	if out == "" {
		out = "v8link"
	}
	return out
}
