// Package v8dist contains the version-pinned metadata and shared logic used to
// fetch the prebuilt V8 static libraries for a given GOOS/GOARCH target.
//
// The V8 archives are NOT committed to the repository. They are published as
// GitHub Release assets by CI and downloaded on demand into a project-local
// .v8/ directory by the v8setup tool (invoked via `go generate`).
package v8dist

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

//go:embed manifest.json
var manifestBytes []byte

// Target describes a single prebuilt V8 artifact for one GOOS/GOARCH pair.
type Target struct {
	GOOS     string `json:"goos"`
	GOARCH   string `json:"goarch"`
	Filename string `json:"filename"`
	SHA256   string `json:"sha256"`
}

// Manifest is the version-pinned distribution metadata embedded in the module.
// It is generated by the update workflow (scripts/gen-manifest.py) and drives
// both the download URL and the versioned on-disk layout.
type Manifest struct {
	// V8Version is the upstream V8 tag the libraries were built from.
	V8Version string `json:"v8_version"`
	// ModuleVersion is the semantic version tag (e.g. "v1.4.2") of this module
	// and of the GitHub Release that hosts the artifacts.
	ModuleVersion string `json:"module_version"`
	// SourceCommit is the commit the artifacts were built from.
	SourceCommit string `json:"source_commit"`
	// SourceRunID is the GitHub Actions run id that produced the artifacts.
	// It lets PR validation download the exact artifacts before a Release exists.
	SourceRunID string `json:"source_run_id"`
	// Owner/Repo identify the GitHub repository hosting the Releases (this can
	// differ from the vanity module path).
	Owner string `json:"owner"`
	Repo  string `json:"repo"`
	// Targets lists the supported platforms and their per-artifact checksums.
	Targets []Target `json:"targets"`
}

// LoadManifest parses the embedded manifest.json.
func LoadManifest() (*Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(manifestBytes, &m); err != nil {
		return nil, fmt.Errorf("v8dist: parsing embedded manifest: %w", err)
	}
	return &m, nil
}

// TargetFor returns the artifact metadata for the given goos/goarch, or an
// error listing the supported targets if none matches.
func (m *Manifest) TargetFor(goos, goarch string) (Target, error) {
	for _, t := range m.Targets {
		if t.GOOS == goos && t.GOARCH == goarch {
			return t, nil
		}
	}
	supported := make([]string, 0, len(m.Targets))
	for _, t := range m.Targets {
		supported = append(supported, t.GOOS+"/"+t.GOARCH)
	}
	return Target{}, &UnsupportedTargetError{
		GOOS:      goos,
		GOARCH:    goarch,
		Supported: supported,
	}
}

// Tag is the git tag / GitHub Release name that hosts the artifacts.
func (m *Manifest) Tag() string { return m.ModuleVersion }
